### PR TITLE
add cf and qspectre flags

### PR DESCRIPTION
**Pull request by TylerLeonhardt**

### CODE REVIEW

**Comment by deepak1556** [comment]
Windows CI requires change similar to https://github.com/microsoft/vscode/blob/a05babfa55a132b26d97019e9936cf0501a5fd19/.github/workflows/ci.yml#L61-L66 to use 2022 toolchain from `windows-latest` agent.

**Comment by alexdima** [comment]
@TylerLeonhardt @deepak1556 I'm a bit out of the loop here. This native node module is one of many native node modules that we ship with VS Code. Should these flags be added to the `yarn` invocation (in the VS Code build) to cover all native node modules, not just those that are owned by us?

**Comment by deepak1556** [comment]
@alexdima we could definitely add these flags in the vscode CI rather than addressing them individually. The advantage of the current method is that we get to run the tests of these individual modules and make sure the flags does not regress any behavior whereas we can only guarantee compile time failures if we do it in vscode CI.

Also after going through our native module list, there are only two of them which we don't own currently and we have decided to ignore them from the BinSkim pipeline https://github.com/microsoft/vscode-internalbacklog/issues/2767.

**Comment by deepak1556** [comment]
Should be rebased once https://github.com/microsoft/node-native-keymap/pull/40 gets merged, for testing.

**Review by deepak1556 — APPROVED** [review]

**Comment by TylerLeonhardt** [comment]
@alexdima need anything else before merging?

**Comment by alexdima** [comment]
Continued in https://github.com/microsoft/vscode/pull/144669

**Pull request merged**
