### PR TITLE
Support for FreeBSD

### PR DESCRIPTION
**Pull request by WouterDemuynck**
Hey,

I was working on my FreeBSD system and stumbled across an issue building this package. Basically, I've changed the binding.gyp file to properly link against X11 on FreeBSD as well as one source code issue where there was a collision with a globally defined variable in the C++ library.

Kind regards,

Wouter

### CODE REVIEW

**Comment by alexandrudima** [comment]
@WouterDemuynck Thank you, looks brilliant! Can I please ask you to sign the contribution license agreement so I can merge this in? https://cla.microsoft.com

**Comment by WouterDemuynck** [comment]
Certainly, I've just signed it and got the completion e-mail from DocuSign. Do I need to e-mail the PDF to someone?

**Comment by alexandrudima** [comment]
@WouterDemuynck Thanks! Usually, the robot picks that up immediately and adds a `cla-signed` tag. I will follow up with the folks that manage this integration and see what's wrong ... Maybe I've set up this repository incorrectly.

**Comment by alexandrudima** [comment]
Closed and reopened to get the robot to wake up :).

**Comment by alexandrudima** [comment]
Thank you very much again! :heart:

**Comment by WouterDemuynck** [comment]
No problem, happy coding! ;)

**Pull request merged**
