### PR TITLE
Support XK_ISO_Level3_Shift and XK_ISO_Level5_Shift

### PR DESCRIPTION
**Pull request by MaxGyver83**
This PR adds support for `XK_ISO_Level3_Shift` and `XK_ISO_Level5_Shift`.

The `AltGr` key is mapped to `XK_ISO_Level3_Shift` in the default German keyboard layout (and others). The [Neo keyboard layout](https://www.neo-layout.org/) (which is like a German Dvorak) and other layouts derived from it additionally use `XK_ISO_Level5_Shift`. Adding these might make it possible to fix some keyboard layout related bugs in VS Code, p.e. https://github.com/Microsoft/vscode/issues/24043, https://github.com/Microsoft/vscode/issues/23991 (at least for Linux).

The property `withAltGr` now depends on `kLevel3KeyModifierMask` (instead of `kControlKeyModifierMask | kAltKeyModifierMask`). This works for both the default German keyboard layout as well as for the Neo layout. Without this PR it doesn't work for Neo (see https://github.com/microsoft/vscode/issues/24043#issuecomment-612576998).

This PR also considers level 5 in the output. This is only important for layouts that use `XK_ISO_Level5_Shift`, like Neo.

I have added `withLevel3Level5` as sixth property (instead of the expected `withShiftLevel5`) because the latter seems to have no relevance but the former corresponds layer 6 in the Neo keyboard layout.

| Property     | Layer in Neo    |
| --------|---------|
| `value` | 1 |
| `withShift` | 2 |
| `withAltGr` | 3 |
| `withShiftAltGr` | 5 |
| `withLevel5` | 4 |
| `withLevel3Level5` | 6 |

### CODE REVIEW

**Comment by MaxGyver83** [comment]
I don't have a reviewer. @alexdima : What do you think about this PR?

**Comment by MaxGyver83** [comment]
Is anybody there?

**Comment by alexdima** [comment]
This looks very good! Thank you! :heart:

**Comment by MaxGyver83** [comment]
Thank you for merging!

**Pull request merged**
