### PR TITLE
refactor: use nan bindings

### PR DESCRIPTION
**Pull request by deepak1556**
Required for https://github.com/microsoft/vscode/tree/electron-6.0.x

### CODE REVIEW

**Comment by egamma** [comment]
@deepak1556 @alexandrudima is on paternity leave, back in July. How critical is this change?

//fyi @kieferrm

**Comment by deepak1556** [comment]
@egamma this change is a blocker for electron 6 upgrade, but we can work with targeting the module against the branch instead of an official npm release. 

```json
{
  "dependencies": {
     "native-keymap": "microsoft/node-native-keymap#node_v12"
  }
}
```

So I wouldn't say its critical to review and merge at the moment.

**Comment by egamma** [comment]
@deepak1556 good to know, thanks

**Comment by bpasero** [comment]
Not sure, but maybe @rebornix could also review.

**Comment by alexandrudima** [comment]
@deepak1556 Thank you for your work, but I've decided to adopt N-API which on top of nan, guarantees ABI stability besides source stability.

**Pull request closed without merging**
